language: r
sudo: required

r: bioc-devel
bioc_check: true
env:
  - _R_CHECK_LENGTH_1_LOGIC2_=true _R_CHECK_LENGTH_1_CONDITION=true

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('JinmiaoChenLab/Rphenograph')"
  - Rscript -e "devtools::install_github('jimhester/covr')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
after_success:
  - R -e "covr::codecov()"