language: r
sudo: required

r: bioc-devel
bioc_check: true
env:
  - _R_CHECK_LENGTH_1_LOGIC2_=true _R_CHECK_LENGTH_1_CONDITION=true

r_binary_packages:
  - covr
  - devtools
install:
  - R -e "devtools::install_github('JinmiaoChenLab/Rphenograph')"
after_success:
  - R -e "covr::codecov()"