language: r
sudo: required
cache: packages

r: bioc-devel
bioc_check: true
env:
  - _R_CHECK_LENGTH_1_LOGIC2_=true _R_CHECK_LENGTH_1_CONDITION=true
  
after_success:
  - R -e "covr::codecov()"

r_binary_packages:
  - covr
  - knitr
  - rmarkdown
  - cowplot
  - data.table
  - dplyr
  - ggplot2
  - ggrepel
  - ggridges
  - gridExtra
  - magrittr
  - Matrix
  - matrixStats
  - methods
  - nnls
  - purrr
  - RColorBrewer
  - reshape2
  - Rtsne
  - scales
