language: r
sudo: required
cache: packages

r: bioc-devel
bioc_check: true
env:
  - _R_CHECK_LENGTH_1_LOGIC2_=true _R_CHECK_LENGTH_1_CONDITION=true
  
after_success:
  - R -e "covr::codecov()"

r_binary_packages:
  - BiocStyle
  - covr
  - diffcyt
  - flowWorkspace
  - ggcyto
  - knitr
  - openCyto
  - rmarkdown
  - ComplexHeatmap
  - ConsensusClusterPlus
  - cowplot
  - data.table
  - dyplr
  - ggplot2
  - ggrepel
  - ggridges
  - graphics
  - grDevices
  - grid
  - gridExtra
  - limma
  - magrittr
  - Matrix
  - matrixStats
  - methods
  - nnls
  - purrr
  - RColorBrewer
  - reshape2
  - Rtsne
  - SingleCellExperiment
  - SummarizedExperiment
  - S4Vectors
  - scales
  - scater
  - stats
